"""fix paper tables id identity

Ensure paper_* tables use identity/auto-increment IDs on PostgreSQL.
"""

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0002_fix_paper_tables_id_identity"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLES = [
    "paper_accounts",
    "paper_balances",
    "paper_positions",
    "paper_orders",
    "paper_trades",
    "equity_snapshots",
]


def _add_identity_if_missing(table: str, connection) -> None:
    inspector = sa.inspect(connection)
    cols = {col["name"]: col for col in inspector.get_columns(table)}
    col = cols.get("id")
    if not col:
        return

    identity = col.get("identity")
    default = col.get("default")

    if identity or default:
        return

    op.execute(sa.text(f'ALTER TABLE "{table}" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY'))


def _drop_identity_if_present(table: str, connection) -> None:
    inspector = sa.inspect(connection)
    cols = {col["name"]: col for col in inspector.get_columns(table)}
    col = cols.get("id")
    if not col:
        return

    identity = col.get("identity")
    if not identity:
        return

    op.execute(sa.text(f'ALTER TABLE "{table}" ALTER COLUMN "id" DROP IDENTITY IF EXISTS'))


def upgrade() -> None:
    connection = op.get_bind()
    if connection.dialect.name != "postgresql":
        return

    for table in TABLES:
        _add_identity_if_missing(table, connection)


def downgrade() -> None:
    connection = op.get_bind()
    if connection.dialect.name != "postgresql":
        return

    for table in TABLES:
        _drop_identity_if_present(table, connection)
